version: '3.8'

services:
  llama_server:
    image: ghcr.io/ggml-org/llama.cpp:server-cuda
    container_name: sizzek_llama
    restart: always
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    ports:
      - "8001:8001"
    volumes:
      - ../models:/models
    command: [ "--n-gpu-layers", "99", "-m", "/models/Llama-xLAM-2-8B-fc-r-Q8_0.gguf", "--port", "8001", "--host", "0.0.0.0", "-n", "512", "--jinja", "-v" ]
